name: 'Deleting Resources'

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy all resources'
        required: true

env:
  region: ap-south-1
  
jobs:
  destroy:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      

    - name: Initialize Terraform
      working-directory: child_module/
      run: terraform init
  
    - name: Destroy Resources
      working-directory: child_module/
      run: terraform destroy -var-file=terraform.tfvars  -auto-approve 
      
      

      